version: "3.9"
services:
  server:
    image: employee-creator-backend:latest
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/employee_creator_backend
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:latest
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=Powerade123!
      - MYSQL_DATABASE=employee_creator_backend
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=Powerade123!

networks:
  springmysql-net:
