version: "3.8"

services:
  app:
    build:
      context: ./production
    ports:
      - "8080:8080"
    expose:
      - 8080
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/employee_creator_backend
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Powerade123!
    volumes:
      - .employee-creator-backend/src:/app/src
      - .employee-creator-backend/pom.xml:/app/pom.xml
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:8080/actuator/health || exit 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 5

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: employee_creator_backend
      MYSQL_PASSWORD: Powerade123!
      MYSQL_ROOT_PASSWORD: Powerade123!
    ports:
      - "3308:3306"
    volumes:
      - ./production/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  frontend:
    build:
      context: ./employee-creator-project
    ports:
      - "5173:5173"
    expose:
      - 5173
    volumes:
      - ./employee-creator-project:/app
      - /app/node_modules

volumes:
  mysql-data:
