version: 1
services:
  - type: web
    name: server
    env: docker
    image: employee-creator-backend:latest
    ports:
      - "8080:8080"
    envVars:
      - key: spring.datasource.url
        value: jdbc:mysql://mysqldb:3306/employee_creator_backend
    networks:
      - name: springmysql-net

  - type: pserv
    name: mysqldb
    env: docker
    image: mysql:latest
    networks:
      - name: springmysql-net
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: Powerade123!
      - key: MYSQL_DATABASE
        value: employee_creator_backend
      - key: MYSQL_USER
        value: admin
      - key: MYSQL_PASSWORD
        value: Powerade123!

networks:
  - name: springmysql-net

