export type FormTypes = {
  firstName: string;
  middleName: string;
  lastName: string;
  email: string;
  phoneNumber: string;
  address: string;
  contractType: string;
  startDay: string;
  startMonth: string;
  startYear: string;
  endDay: string;
  endMonth: string;
  endYear: string;
  onGoing: boolean;
  employmentType: string;
  hoursPW: Number;
  datesEmployed: any;
  datesEmployedEnd: any;
};
